<?php

return [
    'admin' => [
        'main'       => 100,
        'home'       => 101,
        'cro'        => 110,
        'cro_create' => 111,
        'cro_list'   => 112,
        'smo'        => 120,
        'smo_create' => 121,
        'smo_list'   => 122,
    ],
    'cro'   => [
        'main'           => 200,
        'home'           => 201,
        'member'         => 210,
        'member_create'  => 211,
        'member_list'    => 212,
        'profile'        => 220,
        'company'        => 221,
        'user'           => 222,
        'billing'        => 223,
        'project'        => 230,
        'project_create' => 231,
        'project_list'   => 232,
        'post_status'    => 233,
    ],
    'smo'   => [
        'main'          => 300,
        'home'          => 301,
        'member'        => 310,
        'member_create' => 311,
        'member_list'   => 312,
        'profile'       => 320,
        'company'       => 321,
        'user'          => 322,
        'post'          => 330,
        'new_post'      => 331,
        'projects'      => 333,
        'project_posts' => 334,
        'subject'       => 340,
        'posts_open'    => 341,
        'posts_closed'  => 342,
    ],
    'pro'   => [
        'home'          => 401,
        'profile'       => 402,
        'company'       => 403,
        'members_index' => 404,
        'members_new'   => 405,
        'projects'      => 406,
    ]
];
